[network]
name = "simnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 1000000000000

[accounts.wallet_1]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 1000000000000

[accounts.wallet_2]  
mnemonic = "sell invite acquire kitten bamboo drastic junk tilt action fragile skin nothing cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 1000000000000