[network]
name = "simnet"

[accounts.deployer]
mnemonic = "fetch outside black test wash cover just actual execute nice door want airport betray quantum stamp fish act pen trust portion fatigue scissors vague"
balance = 100000000000000

[accounts.wallet_1] 
mnemonic = "replace feature future morning burden flip faculty degree thunder picture depend barely"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "increase carbon whisper scale wing ask hello grid casual tone valley grace"  
balance = 100000000000000